# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  push:
    branches:  master 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: build
        run: ./mvnw compile
        
      - name: test
        run: ./mvnw test

